name: unity-buy-sdk

up:
  - ruby: 2.6.0
  - bundler
  - homebrew:
    - doxygen

commands:
  generate:
    syntax:
      argument: type
    desc:   'generate classes from erb class templates'
    run:    scripts/generate.sh
  publish:
    syntax:
      argument: type
    desc:   'Publish a new .unitypackage for the sdk'
    run:    scripts/publish_thin.sh
